Repository home-assistant-libs/python-webrtc-models, pull requests merged in 2024-11, with the labels that each got.

#1 Add RTCIceCandidate
  pyproject.toml
  tests/__snapshots__/test_init.ambr
  tests/fixtures/RTCIceCandidate_candidate.json
  tests/fixtures/RTCIceCandidate_end.json
  tests/test_init.py
  webrtc_models/__init__.py
Labels: enhancement

#13 Enable Python 3.13 for tests
  .github/workflows/ci.yaml
Labels: ci

#2 Add RTCIceCandidateInit and allow setting sdpMid and sdpMLineIndex
  .gitignore
  tests/__snapshots__/test_init.ambr
  tests/fixtures/RTCIceCandidateInit_candidate.json
  tests/fixtures/RTCIceCandidateInit_end.json
  tests/fixtures/RTCIceCandidateInit_invalid.json
  tests/test_init.py
  webrtc_models/__init__.py
Labels: new-feature
